//! SDN Engine — manages DHCP/DNS/PXE services via dnsmasq config generation.
//!
//! For each virtual network with services enabled, generates a dnsmasq config
//! file and can start/stop the daemon on cluster hosts via agent API.

use std::sync::Arc;
use crate::state::ClusterState;
use crate::services::network::NetworkService;

/// Generate a dnsmasq config for a virtual network.
pub fn generate_dnsmasq_config(state: &Arc<ClusterState>, network_id: i64) -> Result<String, String> {
    let db = state.db.lock().map_err(|_| "DB lock error".to_string())?;
    let net = NetworkService::get_network(&db, network_id)?;

    let mut config = String::new();
    config.push_str(&format!("# Auto-generated by VMM-Cluster for network '{}'\n", net.name));
    config.push_str(&format!("# Network: {} GW: {}\n\n", net.subnet, net.gateway));

    // Interface binding (use a bridge or tap per network)
    config.push_str(&format!("interface=vmm-net-{}\n", network_id));
    config.push_str("bind-interfaces\n");
    config.push_str("no-resolv\n\n");

    // DHCP
    if net.dhcp_enabled && !net.dhcp_range_start.is_empty() && !net.dhcp_range_end.is_empty() {
        config.push_str(&format!("dhcp-range={},{},{}\n",
            net.dhcp_range_start, net.dhcp_range_end, net.dhcp_lease_secs));
        config.push_str(&format!("dhcp-option=option:router,{}\n", net.gateway));

        if net.dns_enabled {
            let dns_ip = if net.dns_domain.is_empty() { net.gateway.clone() } else { net.gateway.clone() };
            config.push_str(&format!("dhcp-option=option:dns-server,{}\n", dns_ip));
        }

        // PXE boot options
        if net.pxe_enabled && !net.pxe_boot_file.is_empty() {
            config.push_str(&format!("dhcp-boot={}", net.pxe_boot_file));
            if !net.pxe_next_server.is_empty() {
                config.push_str(&format!(",{}", net.pxe_next_server));
            }
            config.push_str("\n");
            config.push_str("enable-tftp\n");
            if !net.pxe_tftp_root.is_empty() {
                config.push_str(&format!("tftp-root={}\n", net.pxe_tftp_root));
            }
        }

        config.push_str("\n");
    }

    // DNS
    if net.dns_enabled {
        if !net.dns_domain.is_empty() {
            config.push_str(&format!("domain={}\n", net.dns_domain));
            config.push_str("expand-hosts\n");
        }
        if !net.dns_upstream.is_empty() {
            for server in net.dns_upstream.split(',') {
                let s = server.trim();
                if !s.is_empty() {
                    config.push_str(&format!("server={}\n", s));
                }
            }
        } else {
            config.push_str("server=8.8.8.8\n");
            config.push_str("server=8.8.4.4\n");
        }

        // Auto-registered DNS records
        let records = NetworkService::list_dns_records(&db, network_id).unwrap_or_default();
        for record in &records {
            match record.record_type.as_str() {
                "A" => config.push_str(&format!("host-record={},{}\n", record.name, record.value)),
                "CNAME" => config.push_str(&format!("cname={},{}\n", record.name, record.value)),
                _ => {}
            }
        }

        config.push_str("\n");
    }

    // Logging
    config.push_str("log-queries\n");
    config.push_str(&format!("log-facility=/var/log/vmm-dnsmasq-{}.log\n", network_id));

    Ok(config)
}

/// Generate the dnsmasq config file path for a network.
pub fn config_path(network_id: i64) -> String {
    format!("/etc/vmm/dnsmasq-net-{}.conf", network_id)
}

/// Write config and restart dnsmasq for a network (runs on cluster host).
pub fn apply_config(network_id: i64, config: &str) -> Result<(), String> {
    let path = config_path(network_id);

    // Ensure directory exists
    let _ = std::fs::create_dir_all("/etc/vmm");

    std::fs::write(&path, config)
        .map_err(|e| format!("Cannot write dnsmasq config: {}", e))?;

    // Restart dnsmasq instance for this network
    let pid_file = format!("/var/run/vmm-dnsmasq-{}.pid", network_id);
    let status = std::process::Command::new("dnsmasq")
        .args(&["--conf-file", &path, "--pid-file", &pid_file])
        .status();

    match status {
        Ok(s) if s.success() => {
            tracing::info!("SDN: dnsmasq started for network {}", network_id);
            Ok(())
        }
        Ok(s) => Err(format!("dnsmasq exited with code {:?}", s.code())),
        Err(e) => {
            tracing::warn!("SDN: dnsmasq not available ({}). DHCP/DNS config generated but not started.", e);
            Ok(()) // Config is still written, just not activated
        }
    }
}

/// Stop dnsmasq instance for a network.
pub fn stop_service(network_id: i64) {
    let pid_file = format!("/var/run/vmm-dnsmasq-{}.pid", network_id);
    if let Ok(pid_str) = std::fs::read_to_string(&pid_file) {
        if let Ok(pid) = pid_str.trim().parse::<i32>() {
            unsafe { libc::kill(pid, libc::SIGTERM); }
        }
        let _ = std::fs::remove_file(&pid_file);
    }
}
